Email de Adrien [adrien@cin.ufpe.br]

## Aula 10/11/2025

### Foco da disciplina são braços robóticos (parte mecânica deles)

O que é robô?

    - Tem uma parte de hardware (pode ter ou não rodas, braços, etc)
    - Tem uma parte de software
    - Consegue capturar informações do ambiente por meio de sensores
      - Consegue tomar decições baseado nessas informações e interagir com o ambiente para realizar a tarefa proposta e modifica o ambiente.
    -Ps: Robô é uma máquina que consegue ser reprogramada para realizar tarefas distintas.

Exemplos de robôs:

    - Robô aspirador
    - Braço robótico
    - Robô cirurgião
    - Robô explorador (ex: rover em marte)
    - Robô social (ex: robô que interage com humanos)
    - Drones autonômos
    - Robôs industriais

Sitema robôtico:

    - Sensores: Capturam informações do ambiente (ex: câmera, LIDAR, ultrassom, etc)
    - Controlador: Processa as informações dos sensores e toma decisões (ex: microcontrolador, computador embarcado, etc)
    - Atuadores: Executam as ações no ambiente (ex: motores, servos, etc)
  - Robot = Sense -> Think -> Act

Mechanical System

    - Locomotion: Movimento do robô (ex: rodas, pernas (robotica humanoide), asas, etc)
      - Por quê usar penas do robô ao invés de rodas?
        - Terrenos irregulares
        - Escalar obstáculos
        - Não precisar modificar o ambiente
      - Por que usar mãos robóticas ao invés de garras simples?
        - Manipulação mais precisa
        - Capacidade de realizar tarefas complexas como os humanos (depende da aplicação)
    - Manipulation: Interação com objetos (ex: braços, garras, etc)
    - Structure: Estrutura física do robô (ex: chassi, carcaça, etc)

Robos colaborativos:

    - Kynova
      - Robô de 6 graus de liberdade
      - Usado para tarefas de precisão
      - Fácil de programar e integrar com outros sistemas

Robos industrivais:

    - Denso
      - Robô de 6 graus de liberdade
      - Usado em linhas de montagem
      - Alta precisão e repetibilidade
  
Tipos de motôs (act):
    - O que é e para que serve engranagens?
      - Engrenagens são usadas para transmitir torque e velocidade entre eixos
      - Permitem aumentar ou diminuir a velocidade e o torque do motor
      - Permitem mudar a direção do movimento
      - Permitem sincronizar o movimento entre diferentes partes do robô

    - Motores eletricos (mais comuns):
      - Motores DC:
      - Motores AC:
      - Servomotores:
      - Motores de passo:
  
    - Motores pineumáticos:
      - Cilindros pneumáticos:
      - Motores pneumáticos rotativos:
      - Válvulas pneumáticas:

    - Motores hidráulicos (quando precisa de força enorme):
      - Cilindros hidráulicos:
      - Motores hidráulicos rotativos:
      - Válvulas hidráulicas:

    - Atuadores lineares:
    - Ps: escovas de motores são usadas para fazer a comutação elétrica
      - Brushed DC:
        - pontos positivos:
          - mais comuns em robôs pequenos e mais baratos
          - boa eficiência
          - leve
          - Tem bom torque
          - tem escovas que facilitam o controle
        - pontos negativos:
          - Manutenção frequente (escovas desgastam)
          - Menor vida útil

      - Brushless DC (normalmente a melhor opção):
        - pontos positivos:
          - Maior eficiência
          - Menor manutenção (sem escovas)
          - Maior vida útil
          - mais torque
          - mais precisão
        - pontos negativos:
          - Custo mais alto
          - Requer controlador mais complexo e alguns tipos requerem controladores específicos
      - Geared DC
      - Servo motors:
        - tem o motor, sensorde de posição (placa responsável pelo controle) e a engrenagem tudo integrado em um único componente
        - pontos positivos:
          - o servo motor já tem todo o sistema de controle integrado, que corrige a tensão para rodar na posição desejada
          - Alta precisão de controle de posição
          - Bom torque em baixas velocidades
          - Fácil de controlar (feedback integrado, geralmente com encoders, feedback do motor para controle de posição) 
            - Angular position sensor (optical encoder, ajuda a controlar a posição angular do motor):
            - ps: servomotores são usados quando precisa de controle de posição preciso
            - Potentiometer:

      - Stepper motors:
        - pontos positivos:
          - Controle preciso de posição (sem necessidade de feedback)
          - Boa resposta dinâmica
          - Fácil de controlar (passos discretos)
        - pontos negativos:
          - Menor eficiência
          - Menor torque em altas velocidades
          - Pode perder passos sob carga alta

Sensores comuns em robótica (sense):

    - Proprioceptive sensors (sensores internos) (automação tem apenas esses tipos de sensores):
      - Encoders:
      - Giroscópios:
      - Acelerômetros:
      - Sensores de corrente:      
      - Sensor de colisão:
        - quando houver um obstáculo, criará um contato/sinal para o robô parar ou mudar de direção
      - Sensor de colisão 3D:
        - usado para detectar colisões em 3D, geralmente usado em robôs colaborativos para garantir a segurança dos humanos ao redor
      - Sensor Force/Torque:
        - 3-axis forcer sensor
        - 

    - Exteroceptive sensors (sensores externos):
      - Câmeras:
      - LIDAR:
        - fornece informações geométricas do ambiente e a intensidade da reflexão do laser
        - Usa laser para medir distâncias
        - Cria um mapa 3D do ambiente
        - Usado para navegação e mapeamento
        - Range: 5 - 40m
        - O erro típico é de 2cm
        - Diferença entre LIDAR 2D e 3D:
          - LIDAR 2D: escaneia em um plano (ex: robôs móveis)
            - faz 3 revoluções por segundo
            - pontos por segundo : 6000 a 24000
          - LIDAR 3D: escaneia em 3D (ex: mapeamento de ambientes) 
            - pontos por segundo: 300000 a 1000000
        - 
      - Sensor ultrasônico:
        - Emite ondas sonoras e mede o tempo que leva para o eco retornar
        - Usado para medir distância a objetos
        - Funciona entre 2cm e 3m
      - Sensor infravermelho:
        - Como funciona (funciona melhor em preto ou branco):
          - emissor:
            - envia o sinal
          - Detector:
            - recebe o sinal e calcula a distância
          - Funciona entre 10cm e 1m
      - Inertial motion unit (IMU):
        - auxilia a determinar os graus de liberdade do robô
        - combina acelerômetros e giroscópios para fornecer informações sobre a orientação e movimento do robô
      - GPS:
        - Fornece informações de localização global
        - Usado para navegação ao ar livre
        - Precisão de 5 a 10 metros
      - Indoor positioning (IPS):
        - Fornece informações de localização em ambientes internos
        - Usa tecnologias como Wi-Fi, Bluetooth, UWB, etc
        - Precisão de 10cm a 1m
      - Cameras:
        - 2D RGB cameras:
          - Captura imagens em 2D
          - Usado para visão computacional
          - Tem nos celulares, computadores portáteis, etc
        - 3D RGB-D cameras (deeph sensor):
          - Captura imagens em 3D
          - Fornece informações de profundidade
          - Usado para mapeamento e navegação
          - Ex: Kinect, RealSense, etc
          - funciona a curtas distâncias (0.5m a 5m)

Ps: pose é posição + orientação

Control Systems (think):


Robotica na aplicação Industrial:

    - Braço robótico com co-autonomia:
      - manipulação:
        - Usado para montagem:
      - transformação:
        - soldagem, pintura, etc:


Advanced Robotics:

    - Fild robots:
      - Robôs que operam em ambientes não estruturados:
        - Ex: robôs de busca e resgate, robôs agrícolas, etc
      - Robôs que operam em ambientes estruturados:
        - Ex: robôs industriais, robôs de limpeza, etc

Robot Modeling, Planning and Control:

    -Robor modeling (Representação matemática do robô):
      - Cinemática direta e inversa:
      - Dinâmica:
    - Diferença entre caminho e trajetória:
          - Caminho: sequência de pontos no espaço que o robô deve seguir
            - ponto de A para B
          - Trajetória: caminho com informações de tempo e velocidade
    - Planning:
      - Planejamento de caminho:
      - Planejamento de trajetória:
          -Algoritmos de planejamento:
            - A*
            - RRT (Rapidly-exploring Random Tree)
            - PRM (Probabilistic Roadmap)

## Aula 11/11/2025

-  O que é o Braço robótico?
   -  Primeiro tipo de robo construído (inicio da pesquisa em robótica)
   -  A maioria das pesquisas são focadas em braços robóticos e o restante é em robótica móvel
   -  A ideia inicial é usar o braço robótico na industria
   -  Melhor a segurança
   -  Melhorar a produtividade
   -  Mesmo braço robótico ter flexibilidade (poder ser reproramado para fazer outras tarefas)
- Quando usar o braço robótico?
  - Robótica para industria (não dá para ter um ser humano no espaço de ação dele, como o **Denso**):
    - Tarefas repetitivas
    - Tarefas perigosas
    - Tarefas de precisão
      - mil vezes por mil (o ser humano consegue ser preciso, mas o robô é mais preciso na repetição)
    - Tarefas em ambientes hostis
    - Trabalho pesado
    - trabalhar 24h por dia
- Tipos de braços robóticos:
  - robô para cirurgia
  - braços para serem usados em estação industrial
  - industria
- Robôs colaborativos (dá para ter um ser humano no espaço dele como o **Knova**):
  - Terão motores com menor potência
  - Não consegue carregar uma carga tão pesada
  - Motores mais lentos
  - Velocidade menor
- Onde os robôs são mais usados?
  1. Setor eletrônico
  2. Setor automotivo
  3. metalurgica
  4. plascito e químico
  5. Comida -
     1. O menos usado, pois é mais difícil e as comidas são mais frágeis de se manipular
- Robos industrial x robo colaborativos
  - Os industriais são mais usados que os colaborativos
- A maioria dos robôs estão na Ásia
  - principais produtores de eletrônicos 
    - automatizam muito os processos com os robôs


- Estrutura mecânica dos robôs
  - Robôs rígios/serial link:
    - O número de graus de liberdade do robô, tem que ser igual ou maior do Grau de liberdade da ferramenta (o que ele vai manipular no end-efector)
    - A parte dos motores (**juntas**):
      - Uma junta sempre tem apenas *um grau de liberdade*.
      - Tipo de movimento de junta:
        - Revolução
        - Translação
      - Junta ativa:
      - Junta passiva:
        - não tem robô na junta
    - **Elo** que conecta as juntas
    - End-effector:
  - Parallel link:
    - mais preciso, porém mais difícil de manipular
      - Normalmente usado em cirurgia
  - Esferico:
    - 2 rotações
    - 1 translação
  - cartesiano:
    - 3 translações
  - Cilíndrico:
    - 2 translações
    - 1 rotação
  - Anthropomorphic:
    - 3 rotações
      - tronco, ombro, cotovelo
    - 1 translação
      - pulso
    - 2 rotações
      - pulso
  - Strill art plataform:
    - usado em simuladores de voo
    - alta precisão
    - alta rigidez
    - alta carga
    - alta velocidade
    - pequeno espaço de ação
    - cirurgia robótica
- O que é necessário para controlar o motor do braço robótico?
  - Atuador:
    - motores elétricos (mais comuns):
      - Motores DC:
      - Motores AC:
      - Servomotores:
      - Motores de passo:
      - Engranens:
        - Torque:
          - força de rotação do motor
        - Velocidade:
    - Encoder do motor:
      - mede a posição angular do motor
      - mede a velocidade do motor
      - mede a aceleração do motor
      - E corrige a tensão para rodar na velocidade desejada
    - Mais fácil construir um motor rápido, que um motor com torque alto
      - Para ter um motor com torque alto, usa-se engrenagens para aumentar o torque
      - Redução de engrenagens:
        - Aumenta o torque
        - Diminui a velocidade
    - Controllers: 
  
- Basic math with Python
  - Bibliotecas:
    - Numpy
    - Scipy
    - Matplotlib
    - Sympy

  

- Basic math with Python
  - Bibliotecas:
    - Numpy
    - Scipy
    - Matplotlib
    - Sympy

In [7]:
import math

a = [1,5,8,0]
min = - math.inf
for v in a:
    if v > min:
        min = v
print(min)

8


* Usando o math.nan para ser mais eficiente (como o array em C com valores não inicializado, porem com espaço já alocado na memória)

In [8]:
n = 10
array = [math.nan] * n
print(array)
for i in range(n):
    array[i] = 2 * i + 1
print(array)

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [ ]:
math.round(2.5) # arredonda para o mais próximo par (2)

math.fabs(-5) # valor absoluto (5

math.pow(2,3) # 2^3 = 8) -> Potenciação
math.exp(1) # e^1 = 2.718281828459045 -> Exponencial
math.log(8,2) # log base 2 de 8 = 3 -> Logaritmo base 2
math.log2(8) # log base 2 de 8 = 3 -> Logaritmo base 2

In [ ]:
import numpy as np

# multiplicação matricial [ PRECISO ESTUDAR MAIS SOBRE ISSO E SOBRE DIVISÃO DE MATRIZES USANDO NUMPY ]
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
C = np.dot(A,B)
print(C)

[[ 58  64]
 [139 154]]


In [28]:
# Fazendo um random usando numpy com valores específicos

ramdom_numpy = np.random.randn(5) # cria um array com 5 valores aleatórios seguindo uma distribuição normal
print(ramdom_numpy)

random_array = np.random.rand(3,3) # cria uma matriz 3x3 com valores aleatórios entre 0 e 1
print(random_array)

[ 0.85050802  0.40901443 -2.47732384  0.79404085  0.18747783]
[[0.19797324 0.52699792 0.41125693]
 [0.98155508 0.91291883 0.25152104]
 [0.08728721 0.19054122 0.70538474]]


## Aula 12/22/25

- Fundamentos de roboôs manipuladores
  - A camera captura a imagem e o robô precisa saber onde no plano está o objeto que ele precisa pegar
    - Usar visão computacional para identificar o objeto na imagem
    - Passar um referencial de coordenadas do plano da imagem para o referencial do robô
      - Ex: se o objeto está a 10cm a direita e 5cm a frente da camera, onde está essa posição no referencial do robô?
        - Precisa saber a posição e orientação da camera em relação ao robô
        - Precisa saber a posição e orientação do objeto em relação a camera
        - Precisa fazer a transformação de coordenadas
          - Translação
          - Rotação
          - Escala
          - Shear
    - Fazer a transformação do referencial A para o referencial B:
      - 

In [ ]:
import numpy as np
import math

# matrix de transformação quando tem apenas uma translação em 2d

def SE2_xy(x,y):
    cos = math.cos
    sin = math.sin
    

# A função que representa unicamente uma única rotação em 2d

- Rotação positiva:
  - Quando o x vai b 

## Aula 13/11/25

- Componentes de juntas de um robô:
  - Joint controller
    - exemplo de controlador:
      - raspberry pi
      - arduino
    - Sistema de decisão que compara o valor desejado com o real
    - E envia o sinal para o motor corrigir a posição
  - motor drive
    - a placa que faz de fato a informação chegar no motor, recebendo o comando do controller
  - actuator (engine)
    - Normalmente tem uma caixa de reduçãopara aumentar o torque e adaptar o torque para a situação
    - position sensor
      - Encoder
        - vai contar o número de rotação do eixo do motor
        - compara a posição medida com a posição desejada
          - usa a diferença para corrigir a posição do motor
  - mechanical transmission
- robot motion revisited
  - Configuration space:
    - q = [q1, q2, q3, ..., qn] (a quantidade de q é igual a quantidade de juntas do robô / liberdade do robô)
      - onde cada qi é o valor de uma junta
  - joint space

- robot kinematics
  - Forward kinematics  (cinematica direta):
    - dado o valor das juntas, qual a posição do end-effector?
    - f(q) = x
      - q: joint space
      - x: task space
  - Inverse kinematics (cinematica inversa):
    - dado a posição do end-effector, qual o valor das juntas?
    - f^-1(x) = q
      - x: task space
      - q: joint space

## Aula 14/11/25

- Inverse kinematics
  - Métodos analíticos:
    - Resolver as equações matemáticas que descrevem a cinemática do robô
    - Pode ter múltiplas soluções ou nenhuma solução
    - Exemplo: robô planar de 2 graus de liberdade
  - Métodos numéricos:
    - Usar algoritmos iterativos para encontrar a solução
    - Pode ser mais lento, mas é mais flexível
    - Exemplo: método de Newton-Raphson
  - Métodos baseados em aprendizado de máquina:
    - Usar redes neurais ou outros algoritmos de aprendizado para aprender a relação entre o espaço de tarefas e o espaço de juntas
    - Pode ser mais robusto a ruídos e incertezas
    - Exemplo: rede neural treinada com dados de simulação
  - Esse problema não tem uma receita de bolo
    - Cada estrutura mecânica do robô precisa de um método diferente para resolver a cinemática inversa
    - Calcular a distância entre o end-effector e o alvo usando o triângulo pitagôrico
  - Solução analítica para robô planar 2R:
    - x = l1*cos(q1) + l2*cos(q1 + q2)
    - y = l1*sin(q1) + l2*sin(q1 + q2)
    - Onde:
      - l1: comprimento do primeiro elo
      - l2: comprimento do segundo elo
      - q1: ângulo da primeira junta
      - q2: ângulo da segunda junta
    - Para encontrar q1 e q2 dados x e y, podemos usar as seguintes equações:
      - r = sqrt(x^2 + y^2)
      - cos(q2) = (r^2 - l1^2 - l2^2) / (2 * l1 * l2)
      - sin(q2) = sqrt(1 - cos^2(q2))
      - q2 = atan2(sin(q2), cos(q2))
      - k1 = l1 + l2 * cos(q2)
      - k2 = l2 * sin(q2)
      - q1 = atan2(y, x) - atan2(k2, k1)
    - Solução numérica usando o método de Newton-Raphson:
      - Começar com uma estimativa inicial para q1 e q2
      - Calcular a posição atual do end-effector usando a cinemática direta
      - Calcular o erro entre a posição atual e a posição desejada
      - Calcular a matriz Jacobiana do robô
      - Atualizar os valores de q1 e q2 usando a fórmula:
        - q_new = q_old + J_inv * error
      - Repetir até que o erro seja menor que um limiar pré-definido

## Aula 17/11/25

In [ ]:
#ssh robot@192.168.1.4
#Login: MERCUSYS_ZE45
#Senha: 66880172

In [ ]:
import pigpio
import time

## Aula 19/11/25

#### Prova 
*   Não terá cálculo e nem programação, será de multipla escolha:
    * Motores
    * Sensores
    * Espaço da junta
    * Quantos graus de liberdade tem uma ferramente
    * o que siginfica planejar o espçao da junta
    * matrizes de passagem - 2d e 3d
    * a
* twist - pose(x,y,z roll, pitch, yaw) -> mensagem que representa a velocidade de qualquer corpo em robôtica.
  * linear ->  
    * x
    * y
    * z
  * angular -> ângulos
    * x
    * y
    * z